// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Control.Websockets.Tests")>]
[<assembly: AssemblyProductAttribute("FSharp.Control.Websockets")>]
[<assembly: AssemblyVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-10-02T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","38dcaf681a4c15bd3b76b1f679647b688564c26d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Control.Websockets.Tests"
    let [<Literal>] AssemblyProduct = "FSharp.Control.Websockets"
    let [<Literal>] AssemblyVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-10-02T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.2"
    let [<Literal>] AssemblyInformationalVersion = "0.2.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "38dcaf681a4c15bd3b76b1f679647b688564c26d"
