// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Control.Websockets.Tests")>]
[<assembly: AssemblyProductAttribute("FSharp.Control.Websockets")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2019-09-12T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","186b75184ac273222f755dcea59bd7680d8be72d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Control.Websockets.Tests"
    let [<Literal>] AssemblyProduct = "FSharp.Control.Websockets"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2019-09-12T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyInformationalVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "186b75184ac273222f755dcea59bd7680d8be72d"
