// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Control.Websockets.TPL")>]
[<assembly: AssemblyProductAttribute("FSharp.Control.WebSockets")>]
[<assembly: AssemblyVersionAttribute("0.2.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-09-17T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.3")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","da52e1fd950e50d3ffe499a21fcdc67c49421413")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Control.Websockets.TPL"
    let [<Literal>] AssemblyProduct = "FSharp.Control.WebSockets"
    let [<Literal>] AssemblyVersion = "0.2.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-09-17T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.2.3"
    let [<Literal>] AssemblyInformationalVersion = "0.2.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "da52e1fd950e50d3ffe499a21fcdc67c49421413"
